version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dev_networks

  node-app:
    image: nodejs-express:latest
    # container_name: express-container
    # scale: 2
    depends_on:
      - mongo
      - redis
    environment:
      - HOST=${NODE_HOST}
      - PORT=${NODE_PORT}
      - MONGO_IP=${MONGO_IP}
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_PORT=${MONGO_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    build:
      context: /home/maxl3oss/docker-file/www/express/
    volumes:
      - /home/maxl3oss/docker-file/www/express/:/usr/src/app
      - /app/node_modules
    networks:
      - dev_networks

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO__ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - dev_networks

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - dev_networks

networks:
  dev_networks:


volumes:
  mongodb:
  redisdb: # redisinsightdb:
